# Generated by Django 4.1.1 on 2022-09-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_question_answer_answers_quation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='quation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question'),
        ),
    ]
