# Generated by Django 4.1.1 on 2022-09-20 18:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_extra',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='f3kbfn1ewj0z4oiu3mv3', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='student_extra',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='f3kbfn1ewj0z4oiu3mv3', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teacher_extra',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='f3kbfn1ewj0z4oiu3mv3', max_length=255, verbose_name='image'),
        ),
    ]
