# Generated by Django 4.1.1 on 2022-09-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_admin_extra_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='profile_pic',
            new_name='image_q',
        ),
    ]
