# Generated by Django 4.1.1 on 2022-09-21 12:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_profile_pic_question_image_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_q',
            field=cloudinary.models.CloudinaryField(blank=True, default='andi.png', max_length=255, verbose_name='image'),
        ),
    ]
