# Generated by Django 4.1.1 on 2022-09-21 14:33

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0013_alter_question_image_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_extra',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='student_extra',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='teacher_extra',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='user_extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(default='f3kbfn1ewj0z4oiu3mv3', max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
