# Generated by Django 4.1.1 on 2022-09-21 14:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_admin_extra_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_extra',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='f3kbfn1ewj0z4oiu3mv3', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='student_extra',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='f3kbfn1ewj0z4oiu3mv3', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='teacher_extra',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='f3kbfn1ewj0z4oiu3mv3', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='user_extra',
        ),
    ]
