# Generated by Django 4.1.1 on 2022-09-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_admin_extra_profile_pic_student_extra_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='value',
        ),
    ]
