# Generated by Django 4.1.1 on 2022-09-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_remove_answers_likes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.answers'),
        ),
    ]
