# Generated by Django 4.1.1 on 2022-09-24 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0021_answers_likes_delete_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='answers_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to=settings.AUTH_USER_MODEL),
        ),
    ]
