# Generated by Django 4.1.1 on 2022-09-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_answers_likes_alter_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='value',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
